<a href="https://colab.research.google.com/github/HarshalPawar88/Bankruptcy-Prediction/blob/main/CAPSTONE_COMPANY_BANKRUPTCY_PREDICTION.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# **Problem Statement**

Prediction of bankruptcy is a phenomenon of increasing interest to firms who
stand to loose money because on unpaid debts. Since computers can store huge dataset
pertaining to bankruptcy making accurate predictions from them before hand is becoming
important. 

The data were collected from the Taiwan Economic Journal for the years 1999 to 2009. Company bankruptcy was defined based on the business regulations of the Taiwan Stock Exchange.

 In this project you will use various classification algorithms on bankruptcy
dataset to predict bankruptcies with satisfying accuracies long before the actual event.

# **Attribute Information**

Updated column names and description to make the data easier to understand (Y = Output feature, X = Input features)

Y - Bankrupt?: Class label 1 : Yes , 0: No 

X1 - ROA(C) before interest and depreciation before interest: Return On Total Assets(C)

X2 - ROA(A) before interest and % after tax: Return On Total Assets(A)

X3 - ROA(B) before interest and depreciation after tax: Return On Total Assets(B)

X4 - Operating Gross Margin: Gross Profit/Net Sales

X5 - Realized Sales Gross Margin: Realized Gross Profit/Net Sales

X6 - Operating Profit Rate: Operating Income/Net Sales

X7 - Pre-tax net Interest Rate: Pre-Tax Income/Net Sales

X8 - After-tax net Interest Rate: Net Income/Net Sales

X9 - Non-industry income and expenditure/revenue: Net Non-operating Income Ratio

X10 - Continuous interest rate (after tax): Net Income-Exclude Disposal Gain or Loss/Net Sales

X11 - Operating Expense Rate: Operating Expenses/Net Sales

X12 - Research and development expense rate: (Research and Development Expenses)/Net Sales

X13 - Cash flow rate: Cash Flow from Operating/Current Liabilities

X14 - Interest-bearing debt interest rate: Interest-bearing Debt/Equity

X15 - Tax rate (A): Effective Tax Rate

X16 - Net Value Per Share (B): Book Value Per Share(B)

X17 - Net Value Per Share (A): Book Value Per Share(A)

X18 - Net Value Per Share (C): Book Value Per Share(C)

X19 - Persistent EPS in the Last Four Seasons: EPS-Net Income

X20 - Cash Flow Per Share

X21 - Revenue Per Share (Yuan ¥): Sales Per Share

X22 - Operating Profit Per Share (Yuan ¥): Operating Income Per Share

X23 - Per Share Net profit before tax (Yuan ¥): Pretax Income Per Share

X24 - Realized Sales Gross Profit Growth Rate

X25 - Operating Profit Growth Rate: Operating Income Growth

X26 - After-tax Net Profit Growth Rate: Net Income Growth

X27 - Regular Net Profit Growth Rate: Continuing Operating Income after Tax Growth

X28 - Continuous Net Profit Growth Rate: Net Income-Excluding Disposal Gain or Loss Growth

X29 - Total Asset Growth Rate: Total Asset Growth

X30 - Net Value Growth Rate: Total Equity Growth

X31 - Total Asset Return Growth Rate Ratio: Return on Total Asset Growth

X32 - Cash Reinvestment %: Cash Reinvestment Ratio

X33 - Current Ratio

X34 - Quick Ratio: Acid Test

X35 - Interest Expense Ratio: Interest Expenses/Total Revenue

X36 - Total debt/Total net worth: Total Liability/Equity Ratio

X37 - Debt ratio %: Liability/Total Assets

X38 - Net worth/Assets: Equity/Total Assets

X39 - Long-term fund suitability ratio (A): (Long-term Liability+Equity)/Fixed Assets

X40 - Borrowing dependency: Cost of Interest-bearing Debt

X41 - Contingent liabilities/Net worth: Contingent Liability/Equity

X42 - Operating profit/Paid-in capital: Operating Income/Capital

X43 - Net profit before tax/Paid-in capital: Pretax Income/Capital

X44 - Inventory and accounts receivable/Net value: (Inventory+Accounts Receivables)/Equity

X45 - Total Asset Turnover

X46 - Accounts Receivable Turnover

X47 - Average Collection Days: Days Receivable Outstanding

X48 - Inventory Turnover Rate (times)

X49 - Fixed Assets Turnover Frequency

X50 - Net Worth Turnover Rate (times): Equity Turnover

X51 - Revenue per person: Sales Per Employee

X52 - Operating profit per person: Operation Income Per Employee

X53 - Allocation rate per person: Fixed Assets Per Employee

X54 - Working Capital to Total Assets

X55 - Quick Assets/Total Assets

X56 - Current Assets/Total Assets

X57 - Cash/Total Assets

X58 - Quick Assets/Current Liability

X59 - Cash/Current Liability

X60 - Current Liability to Assets

X61 - Operating Funds to Liability

X62 - Inventory/Working Capital

X63 - Inventory/Current Liability

X64 - Current Liabilities/Liability

X65 - Working Capital/Equity

X66 - Current Liabilities/Equity

X67 - Long-term Liability to Current Assets

X68 - Retained Earnings to Total Assets

X69 - Total income/Total expense

X70 - Total expense/Assets

X71 - Current Asset Turnover Rate: Current Assets to Sales

X72 - Quick Asset Turnover Rate: Quick Assets to Sales

X73 - Working capitcal Turnover Rate: Working Capital to Sales

X74 - Cash Turnover Rate: Cash to Sales

X75 - Cash Flow to Sales

X76 - Fixed Assets to Assets

X77 - Current Liability to Liability

X78 - Current Liability to Equity

X79 - Equity to Long-term Liability

X80 - Cash Flow to Total Assets

X81 - Cash Flow to Liability

X82 - CFO to Assets

X83 - Cash Flow to Equity

X84 - Current Liability to Current Assets

X85 - Liability-Assets Flag: 1 if Total Liability exceeds Total Assets, 0 otherwise

X86 - Net Income to Total Assets

X87 - Total assets to GNP price

X88 - No-credit Interval

X89 - Gross Profit to Sales

X90 - Net Income to Stockholder's Equity

X91 - Liability to Equity

X92 - Degree of Financial Leverage (DFL)

X93 - Interest Coverage Ratio (Interest expense to EBIT)

X94 - Net Income Flag: 1 if Net Income is Negative for the last two years, 0 otherwise

X95 - Equity to Liability

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Mounted at /content/drive


In [2]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import imblearn
from imblearn.under_sampling import NearMiss
from collections import Counter
from sklearn.metrics import classification_report, confusion_matrix, accuracy_score, f1_score, recall_score, precision_score, roc_auc_score
from sklearn.model_selection import GridSearchCV
from imblearn.over_sampling import SMOTE
from sklearn.preprocessing import StandardScaler,MinMaxScaler
from sklearn.model_selection import train_test_split
from sklearn.svm import SVC
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier
from sklearn.ensemble import VotingClassifier
from sklearn.ensemble import RandomForestClassifier
from sklearn.preprocessing import PowerTransformer
pd.options.display.float_format = '{:,.6f}'.format
from imblearn.ensemble import BalancedBaggingClassifier
import warnings
warnings.filterwarnings("ignore")
from sklearn.naive_bayes import GaussianNB
from statsmodels.stats.outliers_influence import variance_inflation_factor
import statsmodels.api as sm

/usr/local/lib/python3.7/dist-packages/sklearn/externals/six.py:31: FutureWarning: The module is deprecated in version 0.21 and will be removed in version 0.23 since we've dropped support for Python 2.7. Please rely on the official version of six (https://pypi.org/project/six/).
  "(https://pypi.org/project/six/).", FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.neighbors.base module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported from sklearn.neighbors. Anything that cannot be imported from sklearn.neighbors is now part of the private API.
  warnings.warn(message, FutureWarning)
/usr/local/lib/python3.7/dist-packages/sklearn/utils/deprecation.py:144: FutureWarning: The sklearn.ensemble.bagging module is  deprecated in version 0.22 and will be removed in version 0.24. The corresponding classes / functions should instead be imported fro

In [3]:
df_1=pd.read_csv('/content/drive/MyDrive/Alma Better/Capstone Project/Copy of COMPANY BANKRUPTCY PREDICTION.csv')

In [4]:
pd.set_option('display.max_columns', 96)
pd.set_option('display.max_rows', 96)
df_1.head(2)

Bankrupt?   ROA(C) before interest and depreciation before interest  \
0          1                                           0.370594          
1          1                                           0.464291          

    ROA(A) before interest and % after tax  \
0                                 0.424389   
1                                 0.538214   

    ROA(B) before interest and depreciation after tax  \
0                                           0.405750    
1                                           0.516730    

    Operating Gross Margin   Realized Sales Gross Margin  \
0                 0.601457                      0.601457   
1                 0.610235                      0.610235   

    Operating Profit Rate   Pre-tax net Interest Rate  \
0                0.998969                    0.796887   
1                0.998946                    0.797380   

    After-tax net Interest Rate   Non-industry income and expenditure/revenue  \
0                      0.808809                                      0.302646   
1                      0.809301                                      0.303556   

    Continuous interest rate (after tax)   Operating Expense Rate  \
0                               0.780985                 0.000126   
1                               0.781506                 0.000290   

    Research and development expense rate   Cash flow rate  \
0                                0.000000         0.458143   
1                                0.000000         0.461867   

    Interest-bearing debt interest rate   Tax rate (A)  \
0                              0.000725       0.000000   
1                              0.000647       0.000000   

    Net Value Per Share (B)   Net Value Per Share (A)  \
0                  0.147950                  0.147950   
1                  0.182251                  0.182251   

    Net Value Per Share (C)   Persistent EPS in the Last Four Seasons  \
0                  0.147950                                  0.169141   
1                  0.182251                                  0.208944   

    Cash Flow Per Share   Revenue Per Share (Yuan ¥)  \
0              0.311664                     0.017560   
1              0.318137                     0.021144   

    Operating Profit Per Share (Yuan ¥)  \
0                              0.095921   
1                              0.093722   

    Per Share Net profit before tax (Yuan ¥)  \
0                                   0.138736   
1                                   0.169918   

    Realized Sales Gross Profit Growth Rate   Operating Profit Growth Rate  \
0                                  0.022102                       0.848195   
1                                  0.022080                       0.848088   

    After-tax Net Profit Growth Rate   Regular Net Profit Growth Rate  \
0                           0.688979                         0.688979   
1                           0.689693                         0.689702   

    Continuous Net Profit Growth Rate   Total Asset Growth Rate  \
0                            0.217535      4,980,000,000.000000   
1                            0.217620      6,110,000,000.000000   

    Net Value Growth Rate   Total Asset Return Growth Rate Ratio  \
0                0.000327                               0.263100   
1                0.000443                               0.264516   

    Cash Reinvestment %   Current Ratio   Quick Ratio  \
0              0.363725        0.002259      0.001208   
1              0.376709        0.006016      0.004039   

    Interest Expense Ratio   Total debt/Total net worth   Debt ratio %  \
0                 0.629951                     0.021266       0.207576   
1                 0.635172                     0.012502       0.171176   

    Net worth/Assets   Long-term fund suitability ratio (A)  \
0           0.792424                               0.005024   
1           0.828824                               0.005059   

    Borrowing depen

In [5]:
print(df_1.isna().sum().sum())
print(np.isnan(df_1).sum().sum())
print(df_1.isnull().sum().sum())

0
0
0


In [6]:
list_1=[]
for i in df_1.columns:
  x=df_1[i].value_counts()
  if len(x)<=2:
    list_1.append(i)
  else:
    continue

In [7]:
list_1

['Bankrupt?', ' Liability-Assets Flag', ' Net Income Flag']

### Liability-Assets Flag

In [8]:
df_1[' Liability-Assets Flag'].unique()
df_1[' Liability-Assets Flag'].value_counts()

0    6811
1       8
Name:  Liability-Assets Flag, dtype: int64

In [9]:
df_1[' Liability-Assets Flag'].value_counts()

0    6811
1       8
Name:  Liability-Assets Flag, dtype: int64

## This feature has a very large class imbalance and we can drop this feature.

## Net Income Flag

In [10]:
df_1[' Net Income Flag'].unique()

array([1])

## This feature has just one unique value and it wont be of any importance.

In [11]:
df_1.drop(columns=[' Net Income Flag', ' Liability-Assets Flag'],inplace=True)

In [12]:
df_1.shape

(6819, 94)

In [13]:
df_1.describe()

Bankrupt?   ROA(C) before interest and depreciation before interest  \
count 6,819.000000                                       6,819.000000          
mean      0.032263                                           0.505180          
std       0.176710                                           0.060686          
min       0.000000                                           0.000000          
25%       0.000000                                           0.476527          
50%       0.000000                                           0.502706          
75%       0.000000                                           0.535563          
max       1.000000                                           1.000000          

        ROA(A) before interest and % after tax  \
count                             6,819.000000   
mean                                  0.558625   
std                                   0.065620   
min                                   0.000000   
25%                                   0.535543   
50%                                   0.559802   
75%                                   0.589157   
max                                   1.000000   

        ROA(B) before interest and depreciation after tax  \
count                                       6,819.000000    
mean                                            0.553589    
std                                             0.061595    
min                                             0.000000    
25%                                             0.527277    
50%                                             0.552278    
75%                                             0.584105    
max                                             1.000000    

        Operating Gross Margin   Realized Sales Gross Margin  \
count             6,819.000000                  6,819.000000   
mean                  0.607948                      0.607929   
std                   0.016934                      0.016916   
min                   0.000000                      0.000000   
25%                   0.600445                      0.600434   
50%                   0.605997                      0.605976   
75%                   0.613914                      0.613842   
max                   1.000000                      1.000000   

        Operating Profit Rate   Pre-tax net Interest Rate  \
count            6,819.000000                6,819.000000   
mean                 0.998755                    0.797190   
std                  0.013010                    0.012869   
min                  0.000000                    0.000000   
25%                  0.998969                    0.797386   
50%                  0.999022                    0.797464   
75%                  0.999095                    0.797579   
max                  1.000000                    1.000000   

        After-tax net Interest Rate  \
count                  6,819.000000   
mean                       0.809084   
std                        0.013601   
min                        0.000000   
25%                        0.809312   
50%                        0.809375   
75%                        0.809469   
max                        1.000000   

        Non-industry income and expenditure/revenue  \
count                                  6,819.000000   
mean                                       0.303623   
std                                        0.011163   
min                                        0.000000   
25%                                        0.303466   
50%                                        0.303525   
75%                                        0.303585   
max                                        1.000000   

        Continuous interest rate (after tax)   Operating Expense Rate  \
count                           6,819.000000             6,819.000000   
mean                                0.781381     1,995,347,312.802792   
std                                 0.012679     3,237,683,890.522487   
min                 

# **Feature Selection**

## **1. Using VIF.**

In [14]:
y=df_1['Bankrupt?']
X_1=df_1.drop(columns='Bankrupt?')

In [16]:
# # VIF dataframe
# vif_data = pd.DataFrame()
# vif_data["feature"] = vif_df.columns

In [17]:
X_1.shape

(6819, 93)

In [18]:
# skewness=PowerTransformer()
# X_1_transformed=pd.DataFrame(skewness.fit_transform(X_1), columns=X_1.columns)
X_1_transformed=X_1.copy()

In [19]:

X_1_transformed.shape

(6819, 93)

In [20]:
#cols_removed_vif=[]
#=[x for x in X_1_transformed.columns if x not in cols_removed_vif]

In [21]:
# columns_after_vif=[x for x in X_1_transformed.columns if x not in cols_removed_vif]

In [22]:
empty_=0
vif_data = pd.DataFrame()
cols_removed_vif=[]
columns_after_vif=[x for x in X_1_transformed.columns]
while empty_ ==0:
 
  # VIF dataframe
  vif_data = pd.DataFrame()
  vif_data["feature"] = columns_after_vif
  vif_data["VIF"] = [variance_inflation_factor(X_1_transformed[columns_after_vif].values, i)
                              for i in range(len(columns_after_vif))]  
  # calculating VIF for each feature
  if np.array(vif_data['VIF'])[-1:]>=15:
    cols_removed_vif.extend([x for x in vif_data.sort_values('VIF')['feature'][-1:] if x not in cols_removed_vif])
    columns_after_vif=[x for x in X_1_transformed.columns if x not in cols_removed_vif]                          
    empty_=0
  else:
    empty_=2


In [23]:
len(columns_after_vif)

93

In [24]:
len(cols_removed_vif)

0

In [25]:
# cols_removed_vif.extend([x for x in vif_data.sort_values('VIF')['feature'][-1:] if x not in cols_removed_vif])
# cols_removed_vif

In [26]:
vif_final=X_1[[x for x in X_1.columns if x not in cols_removed_vif]]

In [27]:
vif_final.shape

(6819, 93)

## **2. Using p_values**

In [28]:
skewness=PowerTransformer(standardize=True)
vif_final_transformed=pd.DataFrame(skewness.fit_transform(vif_final), columns=vif_final.columns)

In [29]:
vif_final_GLM=vif_final_transformed.copy()
vif_final_GLM.set_axis(['x'+str(i) for i in range(0,len(vif_final.columns))], axis='columns', inplace=True)
formula = " Bankrupt ~ "+ '+'.join(vif_final_GLM.columns)
vif_final_GLM['Bankrupt']=y

In [30]:
model = sm.GLM.from_formula(formula, family=sm.families.Binomial(), data=vif_final_GLM)
result = model.fit()
#result.summary() 

In [31]:
p_val=pd.DataFrame(zip(vif_final_transformed.columns,result.pvalues[1:]),columns=['column','p_values'])
columns_based_on_p_and_vif=[x for x in p_val[p_val.p_values<=0.05]['column']]
len(columns_based_on_p_and_vif)

20

## **3. Using on L1 Regularization.**

In [32]:
skewness=PowerTransformer(standardize=False)
vif_final=pd.DataFrame(skewness.fit_transform(vif_final), columns=vif_final.columns)

In [33]:
X_train, X_test, y_train, y_test=train_test_split(vif_final,y,test_size=0.25,stratify=y, random_state=43)

In [34]:
X_train.shape

(5114, 93)

In [35]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [36]:
lr=LogisticRegression(penalty='l1',solver='saga',class_weight='balanced',C=0.01)
lr.fit(X_train,y_train)
y_train_pred=lr.predict(X_train)
y_test_pred=lr.predict(X_test)
print(confusion_matrix(y_train,y_train_pred))
print(classification_report(y_train,y_train_pred))
print(confusion_matrix(y_test,y_test_pred))
print(classification_report(y_test,y_test_pred))

[[4226  723]
 [  18  147]]
              precision    recall  f1-score   support

           0       1.00      0.85      0.92      4949
           1       0.17      0.89      0.28       165

    accuracy                           0.86      5114
   macro avg       0.58      0.87      0.60      5114
weighted avg       0.97      0.86      0.90      5114

[[1406  244]
 [   3   52]]
              precision    recall  f1-score   support

           0       1.00      0.85      0.92      1650
           1       0.18      0.95      0.30        55

    accuracy                           0.86      1705
   macro avg       0.59      0.90      0.61      1705
weighted avg       0.97      0.86      0.90      1705



In [37]:
lr.coef_

array([[-0.02479326, -0.01104881, -0.18707185,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        , -0.01453703,
         0.        ,  0.        ,  0.        , -0.38580146,  0.        ,
        -0.01651382,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        , -0.01389611,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.13551777,  0.22841157, -0.24995479,  0.        ,  0.        ,
         0.        ,  0.        , -0.08982527,  0.        , -0.1610681 ,
        -0.02900015,  0.        ,  0.        ,  0.0011994 ,  0.        ,
         0.        ,  0.        ,  0.21738796,  0.        ,  0.        ,
         0.        , -0.18611409,  0.        ,  0.02480708,  0.13770406,
         0.        , -0.03098199,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        , -0.1337936 ,  0. 

In [38]:
coef_df=pd.DataFrame(zip(vif_final[columns_based_on_p_and_vif].columns,lr.coef_.reshape(-1,1)),columns=['column','coeff'])
columns_after_vif_l1=[x for x in coef_df[coef_df.coeff!=0]['column']]
len(columns_after_vif_l1)

5

In [39]:
roc_auc_score(y_test,y_test_pred)

0.8987878787878787

# **Logistic Regression**

In [45]:
#[columns_based_on_p]
#[coef_columns]

In [46]:
skewness=PowerTransformer(standardize=True)
X_1=pd.DataFrame(skewness.fit_transform(X_1), columns=X_1.columns)

In [47]:
X_train, X_test, y_train, y_test=train_test_split(X_1[zq],y,test_size=0.25, stratify=y, random_state=99)


In [48]:
X_train.shape

(5114, 31)

In [49]:
scaler=StandardScaler()
X_train=scaler.fit_transform(X_train)
X_test=scaler.transform(X_test)

In [50]:
# #importing and fitting the data to the PCA
# from sklearn.decomposition import PCA
# pca = PCA(n_components=20)
# pca.fit(X_train)
# # transforming the principal components to the original values
# X_train=pca.transform(X_train)
# X_test=pca.transform(X_test)

In [51]:
lr=LogisticRegression(class_weight='balanced',C=1)
lr.fit(X_train,y_train)
y_train_pred=lr.predict(X_train)
y_test_pred=lr.predict(X_test)
print(confusion_matrix(y_train,y_train_pred))
print(classification_report(y_train,y_train_pred))
print(confusion_matrix(y_test,y_test_pred))
print(classification_report(y_test,y_test_pred))

[[4187  762]
 [  20  145]]
              precision    recall  f1-score   support

           0       1.00      0.85      0.91      4949
           1       0.16      0.88      0.27       165

    accuracy                           0.85      5114
   macro avg       0.58      0.86      0.59      5114
weighted avg       0.97      0.85      0.89      5114

[[1423  227]
 [   9   46]]
              precision    recall  f1-score   support

           0       0.99      0.86      0.92      1650
           1       0.17      0.84      0.28        55

    accuracy                           0.86      1705
   macro avg       0.58      0.85      0.60      1705
weighted avg       0.97      0.86      0.90      1705



In [52]:
lr1=LogisticRegression(class_weight='balanced')
lr_cv=GridSearchCV(estimator=lr1, param_grid={'C':[1,0.5,0.1,0.05,0.01,0.08]},scoring='f1')
lr_cv.fit(X_train,y_train)

GridSearchCV(cv=None, error_score=nan,
             estimator=LogisticRegression(C=1.0, class_weight='balanced',
                                          dual=False, fit_intercept=True,
                                          intercept_scaling=1, l1_ratio=None,
                                          max_iter=100, multi_class='auto',
                                          n_jobs=None, penalty='l2',
                                          random_state=None, solver='lbfgs',
                                          tol=0.0001, verbose=0,
                                          warm_start=False),
             iid='deprecated', n_jobs=None,
             param_grid={'C': [1, 0.5, 0.1, 0.05, 0.01, 0.08]},
             pre_dispatch='2*n_jobs', refit=True, return_train_score=False,
             scoring='f1', verbose=0)

In [53]:
lr_cv.best_params_

{'C': 0.1}

In [54]:
# coef_df=pd.DataFrame(zip(vif_final_transformed.columns,lr.coef_.reshape(-1,1)),columns=['column','coeff'])
# coef_columns=[x for x in coef_df[coef_df.coeff>0]['column']]

In [55]:
# coef_columns

## 2.SVM

In [56]:
X_train.shape

(5114, 31)

In [57]:
svm_mod=SVC(kernel='poly',C=0.1, class_weight='balanced',gamma=0.08)
svm_mod.fit(X_train,y_train)
y_train_pred_svm=svm_mod.predict(X_train)
y_test_pred_svm=svm_mod.predict(X_test)

In [58]:
print(confusion_matrix(y_train,y_train_pred_svm))
print(classification_report(y_train,y_train_pred_svm))
print(confusion_matrix(y_test,y_test_pred_svm))
print(classification_report(y_test,y_test_pred_svm))

[[4665  284]
 [   6  159]]
              precision    recall  f1-score   support

           0       1.00      0.94      0.97      4949
           1       0.36      0.96      0.52       165

    accuracy                           0.94      5114
   macro avg       0.68      0.95      0.75      5114
weighted avg       0.98      0.94      0.96      5114

[[1559   91]
 [  30   25]]
              precision    recall  f1-score   support

           0       0.98      0.94      0.96      1650
           1       0.22      0.45      0.29        55

    accuracy                           0.93      1705
   macro avg       0.60      0.70      0.63      1705
weighted avg       0.96      0.93      0.94      1705



In [59]:
# oversample = SMOTE()
# X_train, y_train = oversample.fit_resample(X_train, y_train)

In [60]:
estimator = []

estimator.append(('LR', LogisticRegression(C=0.1,class_weight='balanced')))
estimator.append(('Naive', GaussianNB()))
estimator.append(('SVC1', SVC(kernel='linear',C=0.11, class_weight='balanced',gamma=0.01, probability=True)))
estimator.append(('RFC1', RandomForestClassifier(n_estimators=500, criterion = 'gini', class_weight='balanced')))

  
# Voting Classifier with hard voting
vot_hard = VotingClassifier(estimators = estimator, voting ='hard')
vot_hard.fit(X_train, y_train)
y_pred = vot_hard.predict(X_test)
  
# using accuracy_score metric to predict accuracy
score = accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))
  
# Voting Classifier with soft voting
vot_soft = VotingClassifier(estimators = estimator, voting ='soft')
vot_soft.fit(X_train, y_train)
y_pred = vot_soft.predict(X_test)
  
# using accuracy_score
score = accuracy_score(y_test, y_pred)
print(classification_report(y_test, y_pred))

              precision    recall  f1-score   support

           0       0.98      0.92      0.95      1650
           1       0.19      0.53      0.28        55

    accuracy                           0.91      1705
   macro avg       0.59      0.73      0.61      1705
weighted avg       0.96      0.91      0.93      1705

              precision    recall  f1-score   support

           0       0.98      0.97      0.98      1650
           1       0.37      0.47      0.42        55

    accuracy                           0.96      1705
   macro avg       0.68      0.72      0.70      1705
weighted avg       0.96      0.96      0.96      1705



In [61]:
forest = RandomForestClassifier(class_weight={0:1,1:18})
balbag = BalancedBaggingClassifier(base_estimator = forest, n_estimators = 100, bootstrap = False,  bootstrap_features= True,
                                  replacement = False, random_state = 5)
model_full_sample = balbag.fit(X_train, y_train)

In [62]:
y_pred=model_full_sample.predict(X_test)
print(confusion_matrix(y_test,y_pred))
print(classification_report(y_test,y_pred))

[[1447  203]
 [  13   42]]
              precision    recall  f1-score   support

           0       0.99      0.88      0.93      1650
           1       0.17      0.76      0.28        55

    accuracy                           0.87      1705
   macro avg       0.58      0.82      0.61      1705
weighted avg       0.96      0.87      0.91      1705

